In [1]:
import nltk
import numpy as np
import pandas as pd

In [2]:
from nltk.corpus import brown

In [3]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [4]:
#brown.fileids()

In [5]:
data=brown.sents(categories='news')[1:100]

In [6]:
 nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\twink\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [7]:
text="it was a very pleasent day ,the weather was cool and there were light showers. I went to the market to buy some fruits"

In [8]:
from nltk.tokenize import sent_tokenize,word_tokenize


In [9]:
sentences=sent_tokenize(text)

In [10]:
sentences


['it was a very pleasent day ,the weather was cool and there were light showers.',
 'I went to the market to buy some fruits']

In [11]:
words=word_tokenize(sentences[0].lower())

In [12]:
words

['it',
 'was',
 'a',
 'very',
 'pleasent',
 'day',
 ',',
 'the',
 'weather',
 'was',
 'cool',
 'and',
 'there',
 'were',
 'light',
 'showers',
 '.']

# Stop word removal

In [13]:
from nltk.corpus import stopwords

In [14]:
sws=set(stopwords.words('english'))

In [15]:
print(len(sws))

179


In [16]:
sws

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [17]:
useful_words=[w for w in words if w not in sws]

In [18]:
useful_words

['pleasent', 'day', ',', 'weather', 'cool', 'light', 'showers', '.']

# using a regular language tokenizer

In [19]:
from nltk.tokenize import RegexpTokenizer

In [20]:
reg_tokenize=RegexpTokenizer("[a-zA-Z]+")

In [21]:
text_tokenized=reg_tokenize.tokenize(sentences[0])

In [22]:
text_tokenized

['it',
 'was',
 'a',
 'very',
 'pleasent',
 'day',
 'the',
 'weather',
 'was',
 'cool',
 'and',
 'there',
 'were',
 'light',
 'showers']

In [23]:
useful_words_2=[w for w in text_tokenized if w not in sws]

In [24]:
useful_words_2

['pleasent', 'day', 'weather', 'cool', 'light', 'showers']

In [25]:
text="""Where did he learn to dance like that?',
        'His eyes were dancing with humor.',
        'She shook her head and danced away',
        'Alex was an excellent dancer. """


In [26]:
word_list=reg_tokenize.tokenize(text.lower())

In [27]:
word_list

['where',
 'did',
 'he',
 'learn',
 'to',
 'dance',
 'like',
 'that',
 'his',
 'eyes',
 'were',
 'dancing',
 'with',
 'humor',
 'she',
 'shook',
 'her',
 'head',
 'and',
 'danced',
 'away',
 'alex',
 'was',
 'an',
 'excellent',
 'dancer']

In [28]:
word_list=[w for w in word_list if w not in sws]

In [29]:
word_list# only usedul words but has other root words

['learn',
 'dance',
 'like',
 'eyes',
 'dancing',
 'humor',
 'shook',
 'head',
 'danced',
 'away',
 'alex',
 'excellent',
 'dancer']

# Stemming
1)snow ball stemmer
2) porter
3) lancaster

In [30]:
from nltk.stem.snowball import PorterStemmer

In [31]:
 ps=PorterStemmer()

In [32]:
ps.stem("jumping")

'jump'

In [33]:
ps.stem("jumps")

'jump'

In [34]:
ps.stem("awesome")# some dont make sense

'awesom'

In [35]:
stemmer_by_ps=[ps.stem(w) for w in word_list]

In [36]:
stemmer_by_ps

['learn',
 'danc',
 'like',
 'eye',
 'danc',
 'humor',
 'shook',
 'head',
 'danc',
 'away',
 'alex',
 'excel',
 'dancer']

In [37]:
from nltk.stem.lancaster import LancasterStemmer


In [38]:
ls=LancasterStemmer()

In [39]:
stemmer_by_ls=[ls.stem(w) for w in word_list]
stemmer_by_ls# different results

['learn',
 'dant',
 'lik',
 'ey',
 'dant',
 'hum',
 'shook',
 'head',
 'dant',
 'away',
 'alex',
 'excel',
 'dant']

In [40]:
from nltk.stem.snowball import SnowballStemmer
ss=SnowballStemmer(language='english')
stemmer_by_ss=[ss.stem(w.strip()) for w in word_list]
print(stemmer_by_ss)

['learn', 'danc', 'like', 'eye', 'danc', 'humor', 'shook', 'head', 'danc', 'away', 'alex', 'excel', 'dancer']


# building common vocalbulary and vectoring documents(Bag of EWords approach)

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
new_text=["We cannot work with text directly when using machine learning algorithms.",

"Instead, we need to convert the text to numbers"
,
"We may want to perform classification of documents, so each document is an “input” and a class label is the “output” for our predictive algorithm. Algorithms take vectors of numbers as input, therefore we need to convert documents to fixed-length vectors of numbers."
,
"A simple and effective model for thinking about text documents in machine learning is called the Bag-of-Words Model, or BoW."
,
"The model is simple in that it throws away all of the order information in the words and focuses on the occurrence of words in a document."
,"This can be done by assigning each word a unique number. Then any document we see can be encoded as a fixed-length vector with the length of the vocabulary of known words. The value in each position in the vector could be filled with a count or frequency of each word in the encoded document  "

,"This is the bag of words model, where we are only concerned with encoding schemes that represent what words are present or the degree to which they are present in encoded documents without any information about order. "
,"There are many ways to extend this simple method, both by better clarifying what a “word” is and in defining what to encode about each word in the vector"

,"The scikit-learn library provides 3 different schemes that we can use, and we will briefly look at each" ]

In [43]:
cv=CountVectorizer()
new_text

['We cannot work with text directly when using machine learning algorithms.',
 'Instead, we need to convert the text to numbers',
 'We may want to perform classification of documents, so each document is an “input” and a class label is the “output” for our predictive algorithm. Algorithms take vectors of numbers as input, therefore we need to convert documents to fixed-length vectors of numbers.',
 'A simple and effective model for thinking about text documents in machine learning is called the Bag-of-Words Model, or BoW.',
 'The model is simple in that it throws away all of the order information in the words and focuses on the occurrence of words in a document.',
 'This can be done by assigning each word a unique number. Then any document we see can be encoded as a fixed-length vector with the length of the vocabulary of known words. The value in each position in the vector could be filled with a count or frequency of each word in the encoded document  ',
 'This is the bag of words mo

In [44]:
vectorised_corpus=cv.fit_transform(new_text).toarray()

In [45]:
print(vectorised_corpus)# each row each word frequency


[[0 0 1 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 2 0]
 [1 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]]


In [46]:
print((sorted(cv.vocabulary_)))# word-> index

['about', 'algorithm', 'algorithms', 'all', 'an', 'and', 'any', 'are', 'as', 'assigning', 'at', 'away', 'bag', 'be', 'better', 'both', 'bow', 'briefly', 'by', 'called', 'can', 'cannot', 'clarifying', 'class', 'classification', 'concerned', 'convert', 'could', 'count', 'defining', 'degree', 'different', 'directly', 'document', 'documents', 'done', 'each', 'effective', 'encode', 'encoded', 'encoding', 'extend', 'filled', 'fixed', 'focuses', 'for', 'frequency', 'in', 'information', 'input', 'instead', 'is', 'it', 'known', 'label', 'learn', 'learning', 'length', 'library', 'look', 'machine', 'many', 'may', 'method', 'model', 'need', 'number', 'numbers', 'occurrence', 'of', 'on', 'only', 'or', 'order', 'our', 'output', 'perform', 'position', 'predictive', 'present', 'provides', 'represent', 'schemes', 'scikit', 'see', 'simple', 'so', 'take', 'text', 'that', 'the', 'then', 'there', 'therefore', 'they', 'thinking', 'this', 'throws', 'to', 'unique', 'use', 'using', 'value', 'vector', 'vectors'

In [47]:
print(vectorised_corpus.shape)

(9, 119)


In [48]:
one_dimensional=vectorised_corpus.reshape((9*119,))

In [49]:
one_dimensional


array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [50]:
print(cv.inverse_transform(vectorised_corpus))

[array(['algorithms', 'cannot', 'directly', 'learning', 'machine', 'text',
       'using', 'we', 'when', 'with', 'work'], dtype='<U14'), array(['convert', 'instead', 'need', 'numbers', 'text', 'the', 'to', 'we'],
      dtype='<U14'), array(['algorithm', 'algorithms', 'an', 'and', 'as', 'class',
       'classification', 'convert', 'document', 'documents', 'each',
       'fixed', 'for', 'input', 'is', 'label', 'length', 'may', 'need',
       'numbers', 'of', 'our', 'output', 'perform', 'predictive', 'so',
       'take', 'the', 'therefore', 'to', 'vectors', 'want', 'we'],
      dtype='<U14'), array(['about', 'and', 'bag', 'bow', 'called', 'documents', 'effective',
       'for', 'in', 'is', 'learning', 'machine', 'model', 'of', 'or',
       'simple', 'text', 'the', 'thinking', 'words'], dtype='<U14'), array(['all', 'and', 'away', 'document', 'focuses', 'in', 'information',
       'is', 'it', 'model', 'occurrence', 'of', 'on', 'order', 'simple',
       'that', 'the', 'throws', 'words'], dty

In [51]:
vector=np.ones((37,))
vector[4:9]=0

In [52]:
print(cv.inverse_transform(vector))

[array(['about', 'algorithm', 'algorithms', 'all', 'assigning', 'at',
       'away', 'bag', 'be', 'better', 'both', 'bow', 'briefly', 'by',
       'called', 'can', 'cannot', 'clarifying', 'class', 'classification',
       'concerned', 'convert', 'could', 'count', 'defining', 'degree',
       'different', 'directly', 'document', 'documents', 'done', 'each'],
      dtype='<U14')]


In [53]:
vector

array([1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [54]:
cv.vocabulary_["we"]

108

In [55]:
print(len(cv.vocabulary_))

119


In [56]:
def myTokenizer(sentence):
    words=reg_tokenize.tokenize(sentence)
    words=[w for w in words if w not in sws]
    return words

In [57]:
for nt in new_text:
    print(myTokenizer(nt.lower()))

['cannot', 'work', 'text', 'directly', 'using', 'machine', 'learning', 'algorithms']
['instead', 'need', 'convert', 'text', 'numbers']
['may', 'want', 'perform', 'classification', 'documents', 'document', 'input', 'class', 'label', 'output', 'predictive', 'algorithm', 'algorithms', 'take', 'vectors', 'numbers', 'input', 'therefore', 'need', 'convert', 'documents', 'fixed', 'length', 'vectors', 'numbers']
['simple', 'effective', 'model', 'thinking', 'text', 'documents', 'machine', 'learning', 'called', 'bag', 'words', 'model', 'bow']
['model', 'simple', 'throws', 'away', 'order', 'information', 'words', 'focuses', 'occurrence', 'words', 'document']
['done', 'assigning', 'word', 'unique', 'number', 'document', 'see', 'encoded', 'fixed', 'length', 'vector', 'length', 'vocabulary', 'known', 'words', 'value', 'position', 'vector', 'could', 'filled', 'count', 'frequency', 'word', 'encoded', 'document']
['bag', 'words', 'model', 'concerned', 'encoding', 'schemes', 'represent', 'words', 'prese

In [58]:
cv2=CountVectorizer(tokenizer=myTokenizer)
#for nn in new_text:
vectorised_corpus_new=cv2.fit_transform(new_text)
print(vectorised_corpus_new) 

  (0, 9)	1
  (0, 81)	1
  (0, 65)	1
  (0, 20)	1
  (0, 71)	1
  (0, 43)	1
  (0, 39)	1
  (0, 1)	1
  (1, 65)	1
  (1, 35)	1
  (1, 48)	1
  (1, 14)	1
  (1, 50)	1
  (2, 1)	1
  (2, 48)	1
  (2, 14)	1
  (2, 50)	2
  (2, 45)	1
  (2, 76)	1
  (2, 54)	1
  (2, 12)	1
  (2, 22)	2
  (2, 21)	1
  (2, 34)	2
  (2, 11)	1
  :	:
  (6, 60)	1
  (6, 59)	1
  (6, 57)	2
  (6, 18)	1
  (6, 78)	1
  (7, 63)	1
  (7, 79)	2
  (7, 73)	1
  (7, 44)	1
  (7, 77)	1
  (7, 28)	1
  (7, 46)	1
  (7, 5)	1
  (7, 10)	1
  (7, 17)	1
  (7, 25)	1
  (8, 60)	1
  (8, 61)	1
  (8, 38)	1
  (8, 41)	1
  (8, 58)	1
  (8, 19)	1
  (8, 70)	1
  (8, 7)	1
  (8, 42)	1


In [59]:
vcv=vectorised_corpus_new[0]
print(vcv.toarray())
print(cv2.inverse_transform(vcv.toarray()))

[[0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1
  0 0 0 0 0 0 0 0 0 1]]
[array(['algorithms', 'cannot', 'directly', 'learning', 'machine', 'text',
       'using', 'work'], dtype='<U14')]


# bi gram , tri gram , n grams

In [60]:
cv3=CountVectorizer(tokenizer=myTokenizer,ngram_range=(1,3))# work with unigram,bigram and trigrams
vectorised_corpus_new=cv3.fit_transform(new_text)
print(cv3.vocabulary_) 

{'cannot': 24, 'work': 293, 'text': 227, 'directly': 59, 'using': 248, 'machine': 146, 'learning': 131, 'algorithms': 3, 'cannot work': 25, 'work text': 294, 'text directly': 228, 'directly using': 60, 'using machine': 249, 'machine learning': 147, 'learning algorithms': 132, 'cannot work text': 26, 'work text directly': 295, 'text directly using': 229, 'directly using machine': 61, 'using machine learning': 250, 'machine learning algorithms': 148, 'instead': 119, 'need': 167, 'convert': 39, 'numbers': 174, 'instead need': 120, 'need convert': 168, 'convert text': 42, 'text numbers': 232, 'instead need convert': 121, 'need convert text': 170, 'convert text numbers': 43, 'may': 153, 'want': 265, 'perform': 186, 'classification': 33, 'documents': 67, 'document': 62, 'input': 114, 'class': 30, 'label': 125, 'output': 183, 'predictive': 192, 'algorithm': 0, 'take': 224, 'vectors': 259, 'therefore': 233, 'fixed': 100, 'length': 135, 'may want': 154, 'want perform': 266, 'perform classificat

In [61]:
print(len(cv3.vocabulary_))

296


In [62]:
print(vectorised_corpus_new[4:50])

  (0, 62)	1
  (0, 217)	1
  (0, 159)	1
  (0, 282)	2
  (0, 239)	1
  (0, 9)	1
  (0, 180)	1
  (0, 110)	1
  (0, 104)	1
  (0, 177)	1
  (0, 163)	1
  (0, 222)	1
  (0, 240)	1
  (0, 10)	1
  (0, 181)	1
  (0, 112)	1
  (0, 284)	1
  (0, 105)	1
  (0, 178)	1
  (0, 283)	1
  (0, 164)	1
  (0, 223)	1
  (0, 241)	1
  (0, 11)	1
  (0, 182)	1
  :	:
  (3, 84)	1
  (4, 206)	1
  (4, 211)	1
  (4, 128)	1
  (4, 142)	1
  (4, 200)	1
  (4, 56)	1
  (4, 245)	1
  (4, 19)	1
  (4, 145)	1
  (4, 212)	1
  (4, 129)	1
  (4, 143)	1
  (4, 201)	1
  (4, 57)	1
  (4, 209)	1
  (4, 246)	1
  (4, 20)	1
  (4, 213)	1
  (4, 130)	1
  (4, 144)	1
  (4, 202)	1
  (4, 58)	1
  (4, 210)	1
  (4, 247)	1


# nf-idf normalizaionm

## weight=tf* idf
# tf(t,d)-> how many times t occurs in docment d
# idf(t,,c ) -> log(1/(1+count(d,t))) => all occurences of t in the corpus c across all the documents in c

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [64]:
tfidf_vctorizer=TfidfVectorizer(tokenizer=myTokenizer,ngram_range=(1,3))

In [65]:
vectorized_corpus=tfidf_vctorizer.fit_transform(new_text)
print(vectorized_corpus.toarray())
print(tfidf_vctorizer.vocabulary_)# each term has some weight

[[0.         0.         0.         ... 0.22708043 0.22708043 0.22708043]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.1142998  0.1142998  0.1142998  ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
{'cannot': 24, 'work': 293, 'text': 227, 'directly': 59, 'using': 248, 'machine': 146, 'learning': 131, 'algorithms': 3, 'cannot work': 25, 'work text': 294, 'text directly': 228, 'directly using': 60, 'using machine': 249, 'machine learning': 147, 'learning algorithms': 132, 'cannot work text': 26, 'work text directly': 295, 'text directly using': 229, 'directly using machine': 61, 'using machine learning': 250, 'machine learning algorithms': 148, 'instead': 119, 'need': 167, 'convert': 39, 'numbers': 174, 'instead need': 120, 'need convert': 168, '